### ISSUE TITLE
[BUG] Messages sent in Discord doesn't appear ingame

### ISSUE THREAD

**Issue by christian1211** [AGuyNamedJens/FactorioChatBot#16]
**Describe the bug**
Messages sent in the Discord channel does't appear ingame. Messages sent ingame do appear in the Discord channel. Also the startup messages appears in Discord channel and also ingame.

**To Reproduce**
Installed everything as described. I cannot find any error message.

**Expected behavior**
Messages sent in the Discord channel should appear ingame.

**Comment by AGuyNamedJens** [comment]
Did you enable the so-called Message intent on the bot at discord's developer portal? They've added that last year

**Comment by christian1211** [comment]
That was the problem, thank you very much!
