### ISSUE TITLE
Bot is unable to connect to the factorio server

### ISSUE THREAD

**Issue by joloman2** [AGuyNamedJens/FactorioChatBot#2]
![afbeelding](https://user-images.githubusercontent.com/64356554/136101343-664b4738-977e-447c-8495-381847087bc8.png)
hi i think i broke the bot somehow can you help me

**Comment by AGuyNamedJens** [comment]
Looks like the bot is no longer connected to the factorio server. Are you sure it's still up?

You should also join my discord at [my discord server](https://jensbot.ovh/discord) instead of making new issues. Would be appreciated!

**Comment by joloman2** [comment]
sure
